repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        # Multi-documents are yaml files with multiple --- separating blocks, like
        # in our docs/parameters.yaml. We need this argument so those parse.
        args: [--allow-multiple-documents]
    -   id: check-added-large-files
        args: ['--maxkb=1024']
-   repo: https://github.com/golangci/golangci-lint
    rev: v1.56.2
    hooks:
    -   id: golangci-lint
